In [4]:
pip install wikipedia

Requirement already satisfied: wikipedia in c:\users\gdas\appdata\local\continuum\anaconda3\lib\site-packages (1.4.0)
Requirement already satisfied: beautifulsoup4 in c:\users\gdas\appdata\local\continuum\anaconda3\lib\site-packages (from wikipedia) (4.7.1)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in c:\users\gdas\appdata\local\continuum\anaconda3\lib\site-packages (from wikipedia) (2.22.0)
Requirement already satisfied: soupsieve>=1.2 in c:\users\gdas\appdata\local\continuum\anaconda3\lib\site-packages (from beautifulsoup4->wikipedia) (1.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\gdas\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gdas\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\gdas\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\gdas\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.8)
Note: you may need to restart the kernel to use updated packages.

In [21]:
import pandas as pd
import wikipedia as wp
import numpy as np

In [14]:
html = wp.page("List of postal codes of Canada: M").html().encode("UTF-8")
df = pd.read_html(html, header = 0)[0]

# Drope the rows with Borough of "Not assigned"
df_assigned = df[df.Borough != 'Not assigned']
df_assigned.reset_index(drop = True, inplace = True)

# Merge rows with the same Postcode
df_assigned = df_assigned.groupby(['Postal code', 'Borough'], as_index=False).agg(lambda x: ', '.join(set(x)))

# Set 'Not assigned' Neigbourhood to be equal to Borough
na_nb_idx =df_assigned['Neighborhood'] == 'Not assigned'
df_assigned.loc[na_nb_idx, 'Neighborhood'] = df_assigned[na_nb_idx].Borough
df_assigned['Neighborhood']=df_assigned['Neighborhood'].str.replace(' / ',',')
df_assigned[df_assigned['Postal code'] == 'M7A']

   Postal code           Borough                                Neighborhood
85         M7A  Downtown Toronto  Queen's Park,Ontario Provincial Government

In [15]:
df_assigned.shape

(103, 3)

In [19]:
df_cord=pd.read_csv('http://cocl.us/Geospatial_data')
df_cord.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [23]:
df_assigned['Latitude'] = np.nan
df_assigned['Longitude'] = np.nan

# For each postcode in df_assigned, find corresponding coordinates in df_cord and assign it to df_assigned
for idx in df_assigned.index:
    cord_idx = df_cord['Postal Code'] == df_assigned.loc[idx, 'Postal code']
    df_assigned.at[idx, 'Latitude'] = df_cord.loc[cord_idx, 'Latitude'].values
    df_assigned.at[idx, 'Longitude'] = df_cord.loc[cord_idx, 'Longitude'].values

# Display the results
df_assigned.head(20)

,Postal code,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern,Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill,Port Union,Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood,Morningside,West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"Kennedy Park,Ionview,East Birchmount Park",43.727929,-79.262029
7,M1L,Scarborough,"Golden Mile,Clairlea,Oakridge",43.711112,-79.284577
8,M1M,Scarborough,"Cliffside,Cliffcrest,Scarborough Village West",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff,Cliffside West",43.692657,-79.264848
10,M1P,Scarborough,"Dorset Park,Wexford Heights,Scarborough Town C...",43.757410,-79.273304
11,M1R,Scarborough,"Wexford,Maryvale",43.750072,-79.295849
12,M1S,Scarborough,Agincourt,43.794200,-79.262029
13,M1T,Scarborough,"Clarks Corners,Tam O'Shanter,Sullivan",43.781638,-79.304302
14,M1V,Scarborough,"Milliken,Agincourt North,Steeles East,L'Amorea...",43.815252,-79.284577
15,M1W,Scarborough,"Steeles West,L'Amoreaux West",43.799525,-79.318389
16,M1X,Scarborough,Upper Rouge,43.836125,-79.205636
17,M2H,North York,Hillcrest Village,43.803762,-79.363452
18,M2J,North York,"Fairview,Henry Farm,Oriole",43.778517,-79.346556
19,M2K,North York,Bayview Village,43.786947,-79.385975